version: '3.8'

services:
  AuthenticationWebApi:
    container_name: AuthenticationWebApi
    image: authentication_webapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_URLS=http://+:80
      - TZ=Asia/Bishkek
    ports:
      - "1001:80"
      # - "1002:443"
    restart: always